Feat/deploy netlify (#13)
* feat: create my first workflow

* fix: run command

* fix: run command

* Enhance GitHub Actions workflow with Node setup

Added steps to checkout the repository, set up Node.js, install dependencies, and run Jest tests.

* fix: run command

* fix: run command

* fix: run command

* feat: rename workflow file

* feat: bump version

* feat: install husky

* feat: execute formtating with pretty-quick on commit

* feat: create pre-push hook

* fix: pull request workflow

* feat: create merge main workflow

* feat: create merge on main workflow

* feat: configure netlify deploy params

* fix: netlify action

* fix: netlify action

* fix: netlify action

* fix: netlify action

* fix: netlify action

diff --git a/.github/workflows/merge-main.yml b/.github/workflows/merge-main.yml
--- a/.github/workflows/merge-main.yml
+++ b/.github/workflows/merge-main.yml
@@ -34,12 +34,13 @@ jobs:
         run: npm run generate
 
       - name: Verify dist
-        run: ls -la dist || echo "dist not found"
+        run: ls -la ./dist || echo "dist not found"
 
       - name: Deploy to Netlify
-        uses: netlify/actions/cli@v3
+        uses: South-Paw/action-netlify-cli@v2
+        id: netlify
+        with:
+          args: 'deploy --dir \"./dist\" --prod'
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
-        with:
-          args: deploy --dir=dist --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
